sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t osallou/my .

script:
  - npm install -g mocha
  - cd tests && docker-compose up -d
  - sleep 120 && mocha -t 10000
  - cd tests && docker-compose down

