sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - mkdir -p manager2/dist
  - docker build -t osallou/my .
  - cd cron && docker build -f Dockerfile-cron -t osallou/mycron .
  - npm install
  - npm install -g eslint

script:
  - eslint routes
  - npm install -g mocha
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose up -d
  - cd $TRAVIS_BUILD_DIR && sleep 180 && docker ps && mocha -t 20000
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose down

