sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t osallou/my .
  - npm install

script:
  - npm install -g mocha
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose up -d
  - cd $TRAVIS_BUILD_DIR && sleep 120 && docker ps && docker logs tests_cron_1 && mocha -t 10000
  - docker logs tests_my_1
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose down

