version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup
          command: |
            mkdir -p manager2/dist
            npm install
            sudo npm install -g eslint
            eslint routes
            eslint core
            sudo npm install -g mocha
            docker build -t osallou/my .
            cd cron && docker build -f Dockerfile-cron -t osallou/mycron .
      - run:
          name: test setup
          command: |
            cd tests
            docker-compose up -d
            for i in {10..0}; do echo Try $i; sleep 30; docker-compose logs my-app | grep "Server listening on port 3000"; if [ $? -eq 0 ] ; then  echo Server is started; nb_done=$(docker-compose exec my-app ls -l /opt/my/scripts/ | grep admin | grep 'update.done' | wc -l); if [ $nb_done -eq 2 ] ; then echo Admin user created; break; fi; fi;  if [ $i -eq 0 ]; then echo Server does not start; exit 1; fi; done
      - run:
          name: run tests
          command: |
            docker ps && mocha -b -t 20000 --full-trace
            cd tests
            docker-compose logs my-app
            docker-compose down
