version: '3'

services:

    mysql:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=my
        ports:
            - "3306:3306"

    mongo:
        image: mongo
        ports:
            - "27017:27017"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

    gomail-rabbitmq:
        image: rabbitmq
        hostname: gomail-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=gomail
            - RABBITMQ_DEFAULT_PASS=gomail

    gomail-redis:
        image: redis
        ports:
            - "6379:6379"

    openldap:
        #image: dinkel/openldap
        image: quay.io/osallou/openldap
        environment:
            - "SLAPD_PASSWORD=my"
            - "SLAPD_DOMAIN=my.org"
        ports:
            - "389:389"
        volumes:
            #- ${MYDIR}/openldap/data/etc:/etc/ldap
            #- ${MYDIR}/openldap/data/lib:/var/lib/ldap
            - ./ldap-data:/etc/ldap/prepopulate:ro
    phpldapadmin:
        #image: dinkel/phpldapadmin
        image: quay.io/osallou/phpldapadmin
        ports:
            - "8080:80"
        environment:
            - LDAP_SERVER_HOST=openldap
